package output

import (
	"fmt"
	"os"
	"strings"

	"github.com/baselinerhq/baseliner/internal/models"
	"github.com/baselinerhq/baseliner/internal/version"
)

// WriteMarkdown writes a Markdown compliance report at path (atomic tmp+rename).
// It is suitable for posting as a control-repo issue or PR comment: a fleet
// summary table (repos x score) plus a findings section per failing repo.
func WriteMarkdown(r *models.RunResult, path string) error {
	content := []byte(buildMarkdown(r))
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, content, 0o644); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// buildMarkdown renders the run as a Markdown report. Status is conveyed in text
// (pass/fail) — no emoji — so it renders identically everywhere.
func buildMarkdown(r *models.RunResult) string {
	var b strings.Builder
	b.WriteString("# baseliner report\n\n")
	fmt.Fprintf(&b, "**%d repo(s) scanned — %d passed, %d failed.** Mean score %.2f.\n\n",
		r.TotalRepos, r.Passed, r.Failed, meanScore(r))
	if r.Privacy != nil {
		verb := "redacted from"
		if r.Privacy.Mode == "exclude" {
			verb = "hidden from"
		}
		fmt.Fprintf(&b, "> %d private repo(s) %s this report.\n\n", r.Privacy.Count, verb)
	}

	// Fleet summary table.
	b.WriteString("| Repo | Score | Coverage | Status | Pass | Fail | Unknown |\n")
	b.WriteString("|------|------:|---------:|:------:|-----:|-----:|--------:|\n")
	for _, repo := range r.Repos {
		pass, fail, unknown := counts(repo)
		status := "pass"
		if fail > 0 {
			status = "fail"
		}
		fmt.Fprintf(&b, "| `%s` | %s | %.0f%% | %s | %d | %d | %d |\n",
			mdEscape(repo.Slug), postureCell(repo), float64(repo.Coverage)*100,
			status, pass, fail, unknown)
	}
	b.WriteString("\n")

	// Findings: one section per repo with failing/errored checks.
	wrote := false
	for _, repo := range r.Repos {
		var fails []models.CheckResult
		for _, c := range repo.Results {
			if c.Status == models.StatusFail || c.Status == models.StatusError {
				fails = append(fails, c)
			}
		}
		if len(fails) == 0 {
			continue
		}
		if !wrote {
			b.WriteString("## Findings\n\n")
			wrote = true
		}
		fmt.Fprintf(&b, "### `%s` — %s\n\n", mdEscape(repo.Slug), postureCell(repo))
		b.WriteString("| Check | Severity | Status | Detail |\n")
		b.WriteString("|-------|----------|--------|--------|\n")
		for _, c := range fails {
			detail := failDetail(c)
			fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
				checkCell(c), c.Severity, c.Status, detail)
		}
		b.WriteString("\n")
	}
	if !wrote {
		b.WriteString("All scanned repositories meet the baseline.\n\n")
	}

	// Waivers: every check a repo waived, so an exception stays visible even
	// on a repo that passes.
	waived := false
	for _, repo := range r.Repos {
		for _, c := range repo.Results {
			if c.Status != models.StatusWaived {
				continue
			}
			if !waived {
				b.WriteString("## Waivers\n\n| Repo | Check | Reason |\n|------|-------|--------|\n")
				waived = true
			}
			reason := ""
			if c.Message != nil {
				reason = mdEscape(*c.Message)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", mdEscape(repo.Slug), checkCell(c), reason)
		}
	}
	if waived {
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	fmt.Fprintf(&b, "_Generated by [baseliner](https://github.com/baselinerhq/baseliner) v%s._\n", version.Version)
	return b.String()
}

// postureCell renders a repo's posture, or "n/a" when nothing was conclusively
// observed, so a report never implies a score that was not measured.
func postureCell(repo models.RepoResult) string {
	posture, ok := repo.Posture()
	if !ok {
		return "n/a"
	}
	return fmt.Sprintf("%.2f", posture)
}

// meanScore is the unweighted mean of per-repo postures, over the repos that
// have one. Repos with no conclusive result are excluded rather than counted as
// zero, which would understate the fleet; 0 when none have a posture.
func meanScore(r *models.RunResult) float64 {
	var sum float64
	n := 0
	for _, repo := range r.Repos {
		if posture, ok := repo.Posture(); ok {
			sum += posture
			n++
		}
	}
	if n == 0 {
		return 0
	}
	return sum / float64(n)
}

// checkCell renders the check id, linked to its policy URL when one is set.
func checkCell(c models.CheckResult) string {
	if c.PolicyURL != "" {
		return fmt.Sprintf("[`%s`](%s)", c.CheckID, c.PolicyURL)
	}
	return "`" + c.CheckID + "`"
}

// failDetail renders the finding message, suffixed with the policy rationale
// (policy_info) when present.
func failDetail(c models.CheckResult) string {
	var msg string
	if c.Message != nil {
		msg = mdEscape(*c.Message)
	}
	if c.PolicyInfo != "" {
		info := mdEscape(c.PolicyInfo)
		if msg == "" {
			return info
		}
		return msg + " — " + info
	}
	return msg
}

// mdEscape neutralizes characters that would break a Markdown table cell.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
