package output

import (
	"strings"
	"testing"
	"time"

	"github.com/baselinerhq/baseliner/internal/models"
)

func TestMarkdownReport(t *testing.T) {
	md := buildMarkdown(sampleRun())
	for _, want := range []string{
		"# baseliner report",
		"**2 repo(s) scanned — 1 passed, 1 failed.**",
		"| `acme/good` | 1.00 | pass |",
		"| `acme/bad` | 0.61 | fail |",
		"## Findings",
		"### `acme/bad` — 0.61",
		"| `readme_exists` | critical | fail | No README file found |",
		"Generated by [baseliner]",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("markdown missing %q in:\n%s", want, md)
		}
	}
	// The fully-passing repo must not get a Findings subsection.
	if strings.Contains(md, "### `acme/good`") {
		t.Error("passing repo should not appear under Findings")
	}
}

func TestMarkdownNoFindings(t *testing.T) {
	ts := time.Date(2026, 6, 17, 4, 0, 0, 0, time.UTC)
	r := &models.RunResult{
		TotalRepos: 1, Passed: 1,
		Repos: []models.RepoResult{{Slug: "acme/ok", Timestamp: ts, Score: 1.0, Results: []models.CheckResult{
			{CheckID: "readme_exists", Status: models.StatusPass, Severity: models.SeverityCritical},
		}}},
	}
	md := buildMarkdown(r)
	if !strings.Contains(md, "All scanned repositories meet the baseline.") {
		t.Errorf("missing all-clear line:\n%s", md)
	}
	if strings.Contains(md, "## Findings") {
		t.Error("no Findings section expected when nothing fails")
	}
}

func TestMarkdownPrivacyNote(t *testing.T) {
	r := sampleRun()
	r.Privacy = &models.PrivacyNote{Mode: "redact", Count: 2}
	if !strings.Contains(buildMarkdown(r), "2 private repo(s) redacted from this report.") {
		t.Error("redact privacy note missing")
	}
	r.Privacy = &models.PrivacyNote{Mode: "exclude", Count: 3}
	if !strings.Contains(buildMarkdown(r), "3 private repo(s) hidden from this report.") {
		t.Error("exclude privacy note missing")
	}
}

func TestMarkdownEscapesPipes(t *testing.T) {
	ts := time.Date(2026, 6, 17, 4, 0, 0, 0, time.UTC)
	msg := "bad | value\nsecond line"
	r := &models.RunResult{
		TotalRepos: 1, Failed: 1,
		Repos: []models.RepoResult{{Slug: "acme/x", Timestamp: ts, Score: 0, Results: []models.CheckResult{
			{CheckID: "c", Status: models.StatusFail, Severity: models.SeverityHigh, Message: &msg},
		}}},
	}
	md := buildMarkdown(r)
	if strings.Contains(md, "bad | value") {
		t.Error("unescaped pipe leaked into a table cell")
	}
	if !strings.Contains(md, "bad \\| value second line") {
		t.Errorf("pipe/newline not escaped as expected:\n%s", md)
	}
}
