package output

import (
	"fmt"
	"os"
	"strings"

	"github.com/baselinerhq/baseliner/internal/models"
	"github.com/baselinerhq/baseliner/internal/version"
)

// WriteMarkdown writes a Markdown compliance report at path (atomic tmp+rename).
// It is suitable for posting as a control-repo issue or PR comment: a fleet
// summary table (repos x score) plus a findings section per failing repo.
func WriteMarkdown(r *models.RunResult, path string) error {
	content := []byte(buildMarkdown(r))
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, content, 0o644); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// buildMarkdown renders the run as a Markdown report. Status is conveyed in text
// (pass/fail) — no emoji — so it renders identically everywhere.
func buildMarkdown(r *models.RunResult) string {
	var b strings.Builder
	b.WriteString("# baseliner report\n\n")
	fmt.Fprintf(&b, "**%d repo(s) scanned — %d passed, %d failed.** Mean score %.2f.\n\n",
		r.TotalRepos, r.Passed, r.Failed, meanScore(r))
	if r.Privacy != nil {
		verb := "redacted from"
		if r.Privacy.Mode == "exclude" {
			verb = "hidden from"
		}
		fmt.Fprintf(&b, "> %d private repo(s) %s this report.\n\n", r.Privacy.Count, verb)
	}

	// Fleet summary table.
	b.WriteString("| Repo | Score | Status | Pass | Fail | Skip |\n")
	b.WriteString("|------|------:|:------:|-----:|-----:|-----:|\n")
	for _, repo := range r.Repos {
		pass, fail, skip := counts(repo)
		status := "pass"
		if fail > 0 {
			status = "fail"
		}
		fmt.Fprintf(&b, "| `%s` | %.2f | %s | %d | %d | %d |\n",
			mdEscape(repo.Slug), float64(repo.Score), status, pass, fail, skip)
	}
	b.WriteString("\n")

	// Findings: one section per repo with failing/errored checks.
	wrote := false
	for _, repo := range r.Repos {
		var fails []models.CheckResult
		for _, c := range repo.Results {
			if c.Status == models.StatusFail || c.Status == models.StatusError {
				fails = append(fails, c)
			}
		}
		if len(fails) == 0 {
			continue
		}
		if !wrote {
			b.WriteString("## Findings\n\n")
			wrote = true
		}
		fmt.Fprintf(&b, "### `%s` — %.2f\n\n", mdEscape(repo.Slug), float64(repo.Score))
		b.WriteString("| Check | Severity | Status | Detail |\n")
		b.WriteString("|-------|----------|--------|--------|\n")
		for _, c := range fails {
			detail := ""
			if c.Message != nil {
				detail = mdEscape(*c.Message)
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s |\n",
				c.CheckID, c.Severity, c.Status, detail)
		}
		b.WriteString("\n")
	}
	if !wrote {
		b.WriteString("All scanned repositories meet the baseline.\n\n")
	}

	b.WriteString("---\n")
	fmt.Fprintf(&b, "_Generated by [baseliner](https://github.com/baselinerhq/baseliner) v%s._\n", version.Version)
	return b.String()
}

// meanScore is the unweighted mean of per-repo scores (0 when there are none).
func meanScore(r *models.RunResult) float64 {
	if len(r.Repos) == 0 {
		return 0
	}
	var sum float64
	for _, repo := range r.Repos {
		sum += float64(repo.Score)
	}
	return sum / float64(len(r.Repos))
}

// mdEscape neutralizes characters that would break a Markdown table cell.
func mdEscape(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}
